FROM mcr.microsoft.com/devcontainers/rust:dev-trixie 

RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y \   
    pkg-config \
    libssl-dev \
    libxkbcommon-dev \   
    libwebkit2gtk-4.1-dev \
    just

RUN git clone https://github.com/pop-os/cosmic-icons.git /tmp/Cosmic
RUN cd /tmp/Cosmic && just install

RUN cd /tmp && wget https://nodejs.org/dist/v22.20.0/node-v22.20.0-linux-x64.tar.xz
RUN tar xvf /tmp/node-v22.20.0-linux-x64.tar.xz
RUN cp -rv node-v22.20.0-linux-x64/* /usr/local/

RUN cd /tmp && wget https://github.com/neovim/neovim/releases/download/v0.11.4/nvim-linux-x86_64.tar.gz
RUN tar xvf /tmp/nvim-linux-x86_64.tar.gz
RUN cp -rv nvim-linux-x86_64/* /usr/local/
